SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `reservator`
  DEFAULT CHARACTER SET utf8;
USE `reservator`;

DROP TABLE IF EXISTS `reservations`;
DROP TABLE IF EXISTS `customers`;
DROP TABLE IF EXISTS `tables`;

CREATE TABLE IF NOT EXISTS `reservations` (
  `id`         INT(11) NOT NULL AUTO_INCREMENT,
  `customerId` INT(11) NOT NULL REFERENCES customers (id),
  `tableId`    INT(11) NOT NULL REFERENCES tables (id),
  `startTime`  TINYBLOB,
  `endTime`    TINYBLOB,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1002;

CREATE TABLE IF NOT EXISTS `customers` (
  `id`          INT(11)     NOT NULL AUTO_INCREMENT,
  `phoneNumber` VARCHAR(12) NOT NULL,
  `name`        VARCHAR(40) NOT NULL,
  `status`      INT(2)      NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1002;

CREATE TABLE IF NOT EXISTS `tables` (
  `id`          INT(11) NOT NULL AUTO_INCREMENT,
  `personCount` INT(2)  NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1002;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;